kind: pipeline
name: default

steps:
- name: build 
  image: golang
  commands:
  - make

- name: create release-source tar
  image: golang
  commands:
    - go mod vendor
    - tar -czf dist/release-source-$DRONE_TAG-DRONE_STAGE_ARCH.tar.gz *
  when:
    event: tag

- name: create release-binary tar
  image: golang
  commands:
    - mkdir dist build
    - DESTDIR=build make install
    - tar -czf dist/release-$DRONE_TAG-$DRONE_STAGE_ARCH.tar.gz build/* init/*
  when:
    event: tag

- name: release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    files:
      - dist/*
    base_url: https://git.saintnet.tech
  when:
    event: tag

